spring:
  elasticsearch:
    uris: http://${ES_HOST:127.0.0.1}:9200    # 连接本机的 ES ，服务器环境使用

# 支付宝沙箱配置
alipay:
  # ======================================
  # 两个回调地址
  # ======================================
  # 同步跳转地址
  return-url: "https://hakimicoding.online/order/detail"
  # 异步回调地址
  notify-url: "https://hakimicoding.online/api/v1/pri/order/pay/callback"


# MyBatis-Plus 配置
mybatis-plus:
  configuration:
    # 开启驼峰命名自动映射 (数据库 flight_no -> Java flightNo)
    map-underscore-to-camel-case: true
    # 打印 SQL 日志
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

